// AUTO-CURATED from the langchain-ai/docs repo (the source of docs.langchain.com).
// Each entry is a real documentation page; `path` fetches live + accurate from
// raw.githubusercontent.com/langchain-ai/docs/main/<path> (CORS-clean, keyless).
// Regenerate with: gh api repos/langchain-ai/docs/git/trees/main?recursive=1
//
// This is the deep-research agent's primary, grounded knowledge base.

export interface DocEntry {
	id: string;
	product: "deepagents" | "langgraph" | "langchain";
	productName: string;
	title: string;
	tags: string[];
	/** Path inside the docs repo; the public URL + raw URL derive from it. */
	path: string;
}

export const DOC_INDEX: DocEntry[] = [
	{ id: "deepagents/a2a", product: "deepagents", productName: "Deep Agents", title: "A2A", tags: ["a2a"], path: "src/oss/deepagents/a2a.mdx" },
	{ id: "deepagents/acp", product: "deepagents", productName: "Deep Agents", title: "ACP", tags: ["acp"], path: "src/oss/deepagents/acp.mdx" },
	{ id: "deepagents/async-subagents", product: "deepagents", productName: "Deep Agents", title: "Async Subagents", tags: ["async","subagents"], path: "src/oss/deepagents/async-subagents.mdx" },
	{ id: "deepagents/backends", product: "deepagents", productName: "Deep Agents", title: "Backends", tags: ["backends"], path: "src/oss/deepagents/backends.mdx" },
	{ id: "deepagents/code-configuration", product: "deepagents", productName: "Deep Agents", title: "Configuration", tags: ["code","configuration"], path: "src/oss/deepagents/code/configuration.mdx" },
	{ id: "deepagents/code-data-locations", product: "deepagents", productName: "Deep Agents", title: "Data Locations", tags: ["code","data","locations"], path: "src/oss/deepagents/code/data-locations.mdx" },
	{ id: "deepagents/code-mcp-tools", product: "deepagents", productName: "Deep Agents", title: "MCP Tools", tags: ["code","mcp","tools"], path: "src/oss/deepagents/code/mcp-tools.mdx" },
	{ id: "deepagents/code-memory-and-skills", product: "deepagents", productName: "Deep Agents", title: "Memory And Skills", tags: ["code","memory","and","skills"], path: "src/oss/deepagents/code/memory-and-skills.mdx" },
	{ id: "deepagents/code-overview", product: "deepagents", productName: "Deep Agents", title: "Overview", tags: ["code","overview"], path: "src/oss/deepagents/code/overview.mdx" },
	{ id: "deepagents/code-providers", product: "deepagents", productName: "Deep Agents", title: "Providers", tags: ["code","providers"], path: "src/oss/deepagents/code/providers.mdx" },
	{ id: "deepagents/code-remote-sandboxes", product: "deepagents", productName: "Deep Agents", title: "Remote Sandboxes", tags: ["code","remote","sandboxes"], path: "src/oss/deepagents/code/remote-sandboxes.mdx" },
	{ id: "deepagents/code-subagents", product: "deepagents", productName: "Deep Agents", title: "Subagents", tags: ["code","subagents"], path: "src/oss/deepagents/code/subagents.mdx" },
	{ id: "deepagents/comparison", product: "deepagents", productName: "Deep Agents", title: "Comparison", tags: ["comparison"], path: "src/oss/deepagents/comparison.mdx" },
	{ id: "deepagents/content-builder", product: "deepagents", productName: "Deep Agents", title: "Content Builder", tags: ["content","builder"], path: "src/oss/deepagents/content-builder.mdx" },
	{ id: "deepagents/context-engineering", product: "deepagents", productName: "Deep Agents", title: "Context Engineering", tags: ["context","engineering"], path: "src/oss/deepagents/context-engineering.mdx" },
	{ id: "deepagents/customization", product: "deepagents", productName: "Deep Agents", title: "Customization", tags: ["customization"], path: "src/oss/deepagents/customization.mdx" },
	{ id: "deepagents/data-analysis", product: "deepagents", productName: "Deep Agents", title: "Data Analysis", tags: ["data","analysis"], path: "src/oss/deepagents/data-analysis.mdx" },
	{ id: "deepagents/deep-research", product: "deepagents", productName: "Deep Agents", title: "Deep Research", tags: ["deep","research"], path: "src/oss/deepagents/deep-research.mdx" },
	{ id: "deepagents/event-streaming", product: "deepagents", productName: "Deep Agents", title: "Event Streaming", tags: ["event","streaming"], path: "src/oss/deepagents/event-streaming.mdx" },
	{ id: "deepagents/frontend-overview", product: "deepagents", productName: "Deep Agents", title: "Overview", tags: ["frontend","overview"], path: "src/oss/deepagents/frontend/overview.mdx" },
	{ id: "deepagents/frontend-sandbox", product: "deepagents", productName: "Deep Agents", title: "Sandbox", tags: ["frontend","sandbox"], path: "src/oss/deepagents/frontend/sandbox.mdx" },
	{ id: "deepagents/frontend-subagent-streaming", product: "deepagents", productName: "Deep Agents", title: "Subagent Streaming", tags: ["frontend","subagent","streaming"], path: "src/oss/deepagents/frontend/subagent-streaming.mdx" },
	{ id: "deepagents/frontend-todo-list", product: "deepagents", productName: "Deep Agents", title: "Todo List", tags: ["frontend","todo","list"], path: "src/oss/deepagents/frontend/todo-list.mdx" },
	{ id: "deepagents/going-to-production", product: "deepagents", productName: "Deep Agents", title: "Going To Production", tags: ["going","to","production"], path: "src/oss/deepagents/going-to-production.mdx" },
	{ id: "deepagents/harness", product: "deepagents", productName: "Deep Agents", title: "Harness", tags: ["harness"], path: "src/oss/deepagents/harness.mdx" },
	{ id: "deepagents/human-in-the-loop", product: "deepagents", productName: "Deep Agents", title: "Human In The Loop", tags: ["human","in","the","loop"], path: "src/oss/deepagents/human-in-the-loop.mdx" },
	{ id: "deepagents/interpreters", product: "deepagents", productName: "Deep Agents", title: "Interpreters", tags: ["interpreters"], path: "src/oss/deepagents/interpreters.mdx" },
	{ id: "deepagents/mcp", product: "deepagents", productName: "Deep Agents", title: "MCP", tags: ["mcp"], path: "src/oss/deepagents/mcp.mdx" },
	{ id: "deepagents/memory", product: "deepagents", productName: "Deep Agents", title: "Memory", tags: ["memory"], path: "src/oss/deepagents/memory.mdx" },
	{ id: "deepagents/models", product: "deepagents", productName: "Deep Agents", title: "Models", tags: ["models"], path: "src/oss/deepagents/models.mdx" },
	{ id: "deepagents/overview", product: "deepagents", productName: "Deep Agents", title: "Overview", tags: ["overview"], path: "src/oss/deepagents/overview.mdx" },
	{ id: "deepagents/permissions", product: "deepagents", productName: "Deep Agents", title: "Permissions", tags: ["permissions"], path: "src/oss/deepagents/permissions.mdx" },
	{ id: "deepagents/profiles", product: "deepagents", productName: "Deep Agents", title: "Profiles", tags: ["profiles"], path: "src/oss/deepagents/profiles.mdx" },
	{ id: "deepagents/quickstart", product: "deepagents", productName: "Deep Agents", title: "Quickstart", tags: ["quickstart"], path: "src/oss/deepagents/quickstart.mdx" },
	{ id: "deepagents/rubric", product: "deepagents", productName: "Deep Agents", title: "Rubric", tags: ["rubric"], path: "src/oss/deepagents/rubric.mdx" },
	{ id: "deepagents/sandboxes", product: "deepagents", productName: "Deep Agents", title: "Sandboxes", tags: ["sandboxes"], path: "src/oss/deepagents/sandboxes.mdx" },
	{ id: "deepagents/skills", product: "deepagents", productName: "Deep Agents", title: "Skills", tags: ["skills"], path: "src/oss/deepagents/skills.mdx" },
	{ id: "deepagents/streaming", product: "deepagents", productName: "Deep Agents", title: "Streaming", tags: ["streaming"], path: "src/oss/deepagents/streaming.mdx" },
	{ id: "deepagents/subagents", product: "deepagents", productName: "Deep Agents", title: "Subagents", tags: ["subagents"], path: "src/oss/deepagents/subagents.mdx" },
	{ id: "deepagents/tools", product: "deepagents", productName: "Deep Agents", title: "Tools", tags: ["tools"], path: "src/oss/deepagents/tools.mdx" },
	{ id: "langchain/academy", product: "langchain", productName: "LangChain", title: "Academy", tags: ["academy"], path: "src/oss/langchain/academy.mdx" },
	{ id: "langchain/agents", product: "langchain", productName: "LangChain", title: "Agents", tags: ["agents"], path: "src/oss/langchain/agents.mdx" },
	{ id: "langchain/component-architecture", product: "langchain", productName: "LangChain", title: "Component Architecture", tags: ["component","architecture"], path: "src/oss/langchain/component-architecture.mdx" },
	{ id: "langchain/context-engineering", product: "langchain", productName: "LangChain", title: "Context Engineering", tags: ["context","engineering"], path: "src/oss/langchain/context-engineering.mdx" },
	{ id: "langchain/deep-agent-from-scratch", product: "langchain", productName: "LangChain", title: "Deep Agent From Scratch", tags: ["deep","agent","from","scratch"], path: "src/oss/langchain/deep-agent-from-scratch.mdx" },
	{ id: "langchain/deploy", product: "langchain", productName: "LangChain", title: "Deploy", tags: ["deploy"], path: "src/oss/langchain/deploy.mdx" },
	{ id: "langchain/event-streaming", product: "langchain", productName: "LangChain", title: "Event Streaming", tags: ["event","streaming"], path: "src/oss/langchain/event-streaming.mdx" },
	{ id: "langchain/frontend-branching-chat", product: "langchain", productName: "LangChain", title: "Branching Chat", tags: ["frontend","branching","chat"], path: "src/oss/langchain/frontend/branching-chat.mdx" },
	{ id: "langchain/frontend-generative-ui", product: "langchain", productName: "LangChain", title: "Generative UI", tags: ["frontend","generative","ui"], path: "src/oss/langchain/frontend/generative-ui.mdx" },
	{ id: "langchain/frontend-headless-tools", product: "langchain", productName: "LangChain", title: "Headless Tools", tags: ["frontend","headless","tools"], path: "src/oss/langchain/frontend/headless-tools.mdx" },
	{ id: "langchain/frontend-human-in-the-loop", product: "langchain", productName: "LangChain", title: "Human In The Loop", tags: ["frontend","human","in","the","loop"], path: "src/oss/langchain/frontend/human-in-the-loop.mdx" },
	{ id: "langchain/frontend-join-rejoin", product: "langchain", productName: "LangChain", title: "Join Rejoin", tags: ["frontend","join","rejoin"], path: "src/oss/langchain/frontend/join-rejoin.mdx" },
	{ id: "langchain/frontend-markdown-messages", product: "langchain", productName: "LangChain", title: "Markdown Messages", tags: ["frontend","markdown","messages"], path: "src/oss/langchain/frontend/markdown-messages.mdx" },
	{ id: "langchain/frontend-message-queues", product: "langchain", productName: "LangChain", title: "Message Queues", tags: ["frontend","message","queues"], path: "src/oss/langchain/frontend/message-queues.mdx" },
	{ id: "langchain/frontend-overview", product: "langchain", productName: "LangChain", title: "Overview", tags: ["frontend","overview"], path: "src/oss/langchain/frontend/overview.mdx" },
	{ id: "langchain/frontend-reasoning-tokens", product: "langchain", productName: "LangChain", title: "Reasoning Tokens", tags: ["frontend","reasoning","tokens"], path: "src/oss/langchain/frontend/reasoning-tokens.mdx" },
	{ id: "langchain/frontend-structured-output", product: "langchain", productName: "LangChain", title: "Structured Output", tags: ["frontend","structured","output"], path: "src/oss/langchain/frontend/structured-output.mdx" },
	{ id: "langchain/frontend-time-travel", product: "langchain", productName: "LangChain", title: "Time Travel", tags: ["frontend","time","travel"], path: "src/oss/langchain/frontend/time-travel.mdx" },
	{ id: "langchain/frontend-tool-calling", product: "langchain", productName: "LangChain", title: "Tool Calling", tags: ["frontend","tool","calling"], path: "src/oss/langchain/frontend/tool-calling.mdx" },
	{ id: "langchain/get-help", product: "langchain", productName: "LangChain", title: "Get Help", tags: ["get","help"], path: "src/oss/langchain/get-help.mdx" },
	{ id: "langchain/guardrails", product: "langchain", productName: "LangChain", title: "Guardrails", tags: ["guardrails"], path: "src/oss/langchain/guardrails.mdx" },
	{ id: "langchain/human-in-the-loop", product: "langchain", productName: "LangChain", title: "Human In The Loop", tags: ["human","in","the","loop"], path: "src/oss/langchain/human-in-the-loop.mdx" },
	{ id: "langchain/install", product: "langchain", productName: "LangChain", title: "Install", tags: ["install"], path: "src/oss/langchain/install.mdx" },
	{ id: "langchain/knowledge-base", product: "langchain", productName: "LangChain", title: "Knowledge Base", tags: ["knowledge","base"], path: "src/oss/langchain/knowledge-base.mdx" },
	{ id: "langchain/long-term-memory", product: "langchain", productName: "LangChain", title: "Long Term Memory", tags: ["long","term","memory"], path: "src/oss/langchain/long-term-memory.mdx" },
	{ id: "langchain/mcp", product: "langchain", productName: "LangChain", title: "MCP", tags: ["mcp"], path: "src/oss/langchain/mcp.mdx" },
	{ id: "langchain/messages", product: "langchain", productName: "LangChain", title: "Messages", tags: ["messages"], path: "src/oss/langchain/messages.mdx" },
	{ id: "langchain/middleware-built-in", product: "langchain", productName: "LangChain", title: "Built In", tags: ["middleware","built","in"], path: "src/oss/langchain/middleware/built-in.mdx" },
	{ id: "langchain/middleware-custom", product: "langchain", productName: "LangChain", title: "Custom", tags: ["middleware","custom"], path: "src/oss/langchain/middleware/custom.mdx" },
	{ id: "langchain/middleware-overview", product: "langchain", productName: "LangChain", title: "Overview", tags: ["middleware","overview"], path: "src/oss/langchain/middleware/overview.mdx" },
	{ id: "langchain/models", product: "langchain", productName: "LangChain", title: "Models", tags: ["models"], path: "src/oss/langchain/models.mdx" },
	{ id: "langchain/multi-agent-custom-workflow", product: "langchain", productName: "LangChain", title: "Custom Workflow", tags: ["multi","agent","custom","workflow"], path: "src/oss/langchain/multi-agent/custom-workflow.mdx" },
	{ id: "langchain/multi-agent-handoffs", product: "langchain", productName: "LangChain", title: "Handoffs", tags: ["multi","agent","handoffs"], path: "src/oss/langchain/multi-agent/handoffs.mdx" },
	{ id: "langchain/multi-agent-handoffs-customer-support", product: "langchain", productName: "LangChain", title: "Handoffs Customer Support", tags: ["multi","agent","handoffs","customer","support"], path: "src/oss/langchain/multi-agent/handoffs-customer-support.mdx" },
	{ id: "langchain/multi-agent-index", product: "langchain", productName: "LangChain", title: "Index", tags: ["multi","agent","index"], path: "src/oss/langchain/multi-agent/index.mdx" },
	{ id: "langchain/multi-agent-router", product: "langchain", productName: "LangChain", title: "Router", tags: ["multi","agent","router"], path: "src/oss/langchain/multi-agent/router.mdx" },
	{ id: "langchain/multi-agent-router-knowledge-base", product: "langchain", productName: "LangChain", title: "Router Knowledge Base", tags: ["multi","agent","router","knowledge","base"], path: "src/oss/langchain/multi-agent/router-knowledge-base.mdx" },
	{ id: "langchain/multi-agent-skills", product: "langchain", productName: "LangChain", title: "Skills", tags: ["multi","agent","skills"], path: "src/oss/langchain/multi-agent/skills.mdx" },
	{ id: "langchain/multi-agent-skills-sql-assistant", product: "langchain", productName: "LangChain", title: "Skills SQL Assistant", tags: ["multi","agent","skills","sql","assistant"], path: "src/oss/langchain/multi-agent/skills-sql-assistant.mdx" },
	{ id: "langchain/multi-agent-subagents", product: "langchain", productName: "LangChain", title: "Subagents", tags: ["multi","agent","subagents"], path: "src/oss/langchain/multi-agent/subagents.mdx" },
	{ id: "langchain/multi-agent-subagents-personal-assistant", product: "langchain", productName: "LangChain", title: "Subagents Personal Assistant", tags: ["multi","agent","subagents","personal","assistant"], path: "src/oss/langchain/multi-agent/subagents-personal-assistant.mdx" },
	{ id: "langchain/observability", product: "langchain", productName: "LangChain", title: "Observability", tags: ["observability"], path: "src/oss/langchain/observability.mdx" },
	{ id: "langchain/overview", product: "langchain", productName: "LangChain", title: "Overview", tags: ["overview"], path: "src/oss/langchain/overview.mdx" },
	{ id: "langchain/philosophy", product: "langchain", productName: "LangChain", title: "Philosophy", tags: ["philosophy"], path: "src/oss/langchain/philosophy.mdx" },
	{ id: "langchain/quickstart", product: "langchain", productName: "LangChain", title: "Quickstart", tags: ["quickstart"], path: "src/oss/langchain/quickstart.mdx" },
	{ id: "langchain/rag", product: "langchain", productName: "LangChain", title: "RAG", tags: ["rag"], path: "src/oss/langchain/rag.mdx" },
	{ id: "langchain/retrieval", product: "langchain", productName: "LangChain", title: "Retrieval", tags: ["retrieval"], path: "src/oss/langchain/retrieval.mdx" },
	{ id: "langchain/runtime", product: "langchain", productName: "LangChain", title: "Runtime", tags: ["runtime"], path: "src/oss/langchain/runtime.mdx" },
	{ id: "langchain/short-term-memory", product: "langchain", productName: "LangChain", title: "Short Term Memory", tags: ["short","term","memory"], path: "src/oss/langchain/short-term-memory.mdx" },
	{ id: "langchain/sql-agent", product: "langchain", productName: "LangChain", title: "SQL Agent", tags: ["sql","agent"], path: "src/oss/langchain/sql-agent.mdx" },
	{ id: "langchain/streaming", product: "langchain", productName: "LangChain", title: "Streaming", tags: ["streaming"], path: "src/oss/langchain/streaming.mdx" },
	{ id: "langchain/structured-output", product: "langchain", productName: "LangChain", title: "Structured Output", tags: ["structured","output"], path: "src/oss/langchain/structured-output.mdx" },
	{ id: "langchain/studio", product: "langchain", productName: "LangChain", title: "Studio", tags: ["studio"], path: "src/oss/langchain/studio.mdx" },
	{ id: "langchain/test-evals", product: "langchain", productName: "LangChain", title: "Evals", tags: ["test","evals"], path: "src/oss/langchain/test/evals.mdx" },
	{ id: "langchain/test-index", product: "langchain", productName: "LangChain", title: "Index", tags: ["test","index"], path: "src/oss/langchain/test/index.mdx" },
	{ id: "langchain/test-integration-testing", product: "langchain", productName: "LangChain", title: "Integration Testing", tags: ["test","integration","testing"], path: "src/oss/langchain/test/integration-testing.mdx" },
	{ id: "langchain/test-unit-testing", product: "langchain", productName: "LangChain", title: "Unit Testing", tags: ["test","unit","testing"], path: "src/oss/langchain/test/unit-testing.mdx" },
	{ id: "langchain/tools", product: "langchain", productName: "LangChain", title: "Tools", tags: ["tools"], path: "src/oss/langchain/tools.mdx" },
	{ id: "langchain/ui", product: "langchain", productName: "LangChain", title: "UI", tags: ["ui"], path: "src/oss/langchain/ui.mdx" },
	{ id: "langchain/voice-agent", product: "langchain", productName: "LangChain", title: "Voice Agent", tags: ["voice","agent"], path: "src/oss/langchain/voice-agent.mdx" },
	{ id: "langgraph/add-memory", product: "langgraph", productName: "LangGraph", title: "Add Memory", tags: ["add","memory"], path: "src/oss/langgraph/add-memory.mdx" },
	{ id: "langgraph/agentic-rag", product: "langgraph", productName: "LangGraph", title: "Agentic RAG", tags: ["agentic","rag"], path: "src/oss/langgraph/agentic-rag.mdx" },
	{ id: "langgraph/application-structure", product: "langgraph", productName: "LangGraph", title: "Application Structure", tags: ["application","structure"], path: "src/oss/langgraph/application-structure.mdx" },
	{ id: "langgraph/backward-compatibility", product: "langgraph", productName: "LangGraph", title: "Backward Compatibility", tags: ["backward","compatibility"], path: "src/oss/langgraph/backward-compatibility.mdx" },
	{ id: "langgraph/case-studies", product: "langgraph", productName: "LangGraph", title: "Case Studies", tags: ["case","studies"], path: "src/oss/langgraph/case-studies.mdx" },
	{ id: "langgraph/checkpointers", product: "langgraph", productName: "LangGraph", title: "Checkpointers", tags: ["checkpointers"], path: "src/oss/langgraph/checkpointers.mdx" },
	{ id: "langgraph/choosing-apis", product: "langgraph", productName: "LangGraph", title: "Choosing Apis", tags: ["choosing","apis"], path: "src/oss/langgraph/choosing-apis.mdx" },
	{ id: "langgraph/deploy", product: "langgraph", productName: "LangGraph", title: "Deploy", tags: ["deploy"], path: "src/oss/langgraph/deploy.mdx" },
	{ id: "langgraph/event-streaming", product: "langgraph", productName: "LangGraph", title: "Event Streaming", tags: ["event","streaming"], path: "src/oss/langgraph/event-streaming.mdx" },
	{ id: "langgraph/fault-tolerance", product: "langgraph", productName: "LangGraph", title: "Fault Tolerance", tags: ["fault","tolerance"], path: "src/oss/langgraph/fault-tolerance.mdx" },
	{ id: "langgraph/frontend-custom-stream-channels", product: "langgraph", productName: "LangGraph", title: "Custom Stream Channels", tags: ["frontend","custom","stream","channels"], path: "src/oss/langgraph/frontend/custom-stream-channels.mdx" },
	{ id: "langgraph/frontend-graph-execution", product: "langgraph", productName: "LangGraph", title: "Graph Execution", tags: ["frontend","graph","execution"], path: "src/oss/langgraph/frontend/graph-execution.mdx" },
	{ id: "langgraph/frontend-overview", product: "langgraph", productName: "LangGraph", title: "Overview", tags: ["frontend","overview"], path: "src/oss/langgraph/frontend/overview.md" },
	{ id: "langgraph/functional-api", product: "langgraph", productName: "LangGraph", title: "Functional API", tags: ["functional","api"], path: "src/oss/langgraph/functional-api.mdx" },
	{ id: "langgraph/graph-api", product: "langgraph", productName: "LangGraph", title: "Graph API", tags: ["graph","api"], path: "src/oss/langgraph/graph-api.mdx" },
	{ id: "langgraph/install", product: "langgraph", productName: "LangGraph", title: "Install", tags: ["install"], path: "src/oss/langgraph/install.mdx" },
	{ id: "langgraph/interrupts", product: "langgraph", productName: "LangGraph", title: "Interrupts", tags: ["interrupts"], path: "src/oss/langgraph/interrupts.mdx" },
	{ id: "langgraph/local-server", product: "langgraph", productName: "LangGraph", title: "Local Server", tags: ["local","server"], path: "src/oss/langgraph/local-server.mdx" },
	{ id: "langgraph/observability", product: "langgraph", productName: "LangGraph", title: "Observability", tags: ["observability"], path: "src/oss/langgraph/observability.mdx" },
	{ id: "langgraph/overview", product: "langgraph", productName: "LangGraph", title: "Overview", tags: ["overview"], path: "src/oss/langgraph/overview.mdx" },
	{ id: "langgraph/persistence", product: "langgraph", productName: "LangGraph", title: "Persistence", tags: ["persistence"], path: "src/oss/langgraph/persistence.mdx" },
	{ id: "langgraph/pregel", product: "langgraph", productName: "LangGraph", title: "Pregel", tags: ["pregel"], path: "src/oss/langgraph/pregel.mdx" },
	{ id: "langgraph/quickstart", product: "langgraph", productName: "LangGraph", title: "Quickstart", tags: ["quickstart"], path: "src/oss/langgraph/quickstart.mdx" },
	{ id: "langgraph/sql-agent", product: "langgraph", productName: "LangGraph", title: "SQL Agent", tags: ["sql","agent"], path: "src/oss/langgraph/sql-agent.mdx" },
	{ id: "langgraph/stores", product: "langgraph", productName: "LangGraph", title: "Stores", tags: ["stores"], path: "src/oss/langgraph/stores.mdx" },
	{ id: "langgraph/streaming", product: "langgraph", productName: "LangGraph", title: "Streaming", tags: ["streaming"], path: "src/oss/langgraph/streaming.mdx" },
	{ id: "langgraph/studio", product: "langgraph", productName: "LangGraph", title: "Studio", tags: ["studio"], path: "src/oss/langgraph/studio.mdx" },
	{ id: "langgraph/test", product: "langgraph", productName: "LangGraph", title: "Test", tags: ["test"], path: "src/oss/langgraph/test.mdx" },
	{ id: "langgraph/thinking-in-langgraph", product: "langgraph", productName: "LangGraph", title: "Thinking In Langgraph", tags: ["thinking","in","langgraph"], path: "src/oss/langgraph/thinking-in-langgraph.mdx" },
	{ id: "langgraph/ui", product: "langgraph", productName: "LangGraph", title: "UI", tags: ["ui"], path: "src/oss/langgraph/ui.mdx" },
	{ id: "langgraph/use-functional-api", product: "langgraph", productName: "LangGraph", title: "Use Functional API", tags: ["use","functional","api"], path: "src/oss/langgraph/use-functional-api.mdx" },
	{ id: "langgraph/use-graph-api", product: "langgraph", productName: "LangGraph", title: "Use Graph API", tags: ["use","graph","api"], path: "src/oss/langgraph/use-graph-api.mdx" },
	{ id: "langgraph/use-subgraphs", product: "langgraph", productName: "LangGraph", title: "Use Subgraphs", tags: ["use","subgraphs"], path: "src/oss/langgraph/use-subgraphs.mdx" },
	{ id: "langgraph/use-time-travel", product: "langgraph", productName: "LangGraph", title: "Use Time Travel", tags: ["use","time","travel"], path: "src/oss/langgraph/use-time-travel.mdx" },
	{ id: "langgraph/workflows-agents", product: "langgraph", productName: "LangGraph", title: "Workflows Agents", tags: ["workflows","agents"], path: "src/oss/langgraph/workflows-agents.mdx" }
];

/** Public docs.langchain.com URL for a page (the citation link). */
export function docUrl(e: DocEntry): string {
	const rel = e.path.replace(/^src\/oss\/(deepagents|langgraph|langchain)\//, "").replace(/\.mdx?$/, "");
	return `https://docs.langchain.com/oss/javascript/${e.product}/${rel}`;
}

/** Raw markdown URL (live, CORS-clean) for fetching the real page content. */
export function docRawUrl(e: DocEntry): string {
	return `https://raw.githubusercontent.com/langchain-ai/docs/main/${e.path}`;
}
